/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ManufacturingRouteImport } from './routes/manufacturing'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InsightIndexRouteImport } from './routes/insight.index'
import { Route as SolutionsSmartMetersRouteImport } from './routes/solutions.smart-meters'
import { Route as SolutionsMdmRouteImport } from './routes/solutions.mdm'
import { Route as SolutionsInteroperabilityRouteImport } from './routes/solutions.interoperability'
import { Route as SolutionsIntelligenceRouteImport } from './routes/solutions.intelligence'
import { Route as SolutionsHesRouteImport } from './routes/solutions.hes'
import { Route as SolutionsCommunicationModulesRouteImport } from './routes/solutions.communication-modules'
import { Route as SolutionsArchitectureRouteImport } from './routes/solutions.architecture'
import { Route as InsightUpdatesRouteImport } from './routes/insight.updates'
import { Route as InsightNewsRouteImport } from './routes/insight.news'
import { Route as InsightArticlesRouteImport } from './routes/insight.articles'
import { Route as InsightSlugRouteImport } from './routes/insight.$slug'
import { Route as IndustriesPowerUtilitiesRouteImport } from './routes/industries.power-utilities'
import { Route as IndustriesGovernmentRouteImport } from './routes/industries.government'
import { Route as ContactLocationsRouteImport } from './routes/contact.locations'
import { Route as ContactDetailsRouteImport } from './routes/contact.details'
import { Route as CompanyOverviewRouteImport } from './routes/company.overview'
import { Route as CompanyLeadershipRouteImport } from './routes/company.leadership'
import { Route as CompanyKaynesRouteImport } from './routes/company.kaynes'
import { Route as CompanyInvestorsRouteImport } from './routes/company.investors'
import { Route as CompanyGovernanceRouteImport } from './routes/company.governance'
import { Route as CompanyCultureRouteImport } from './routes/company.culture'
import { Route as CareersStoriesRouteImport } from './routes/careers.stories'
import { Route as CareersCultureRouteImport } from './routes/careers.culture'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ManufacturingRoute = ManufacturingRouteImport.update({
  id: '/manufacturing',
  path: '/manufacturing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightIndexRoute = InsightIndexRouteImport.update({
  id: '/insight/',
  path: '/insight/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsSmartMetersRoute = SolutionsSmartMetersRouteImport.update({
  id: '/smart-meters',
  path: '/smart-meters',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsMdmRoute = SolutionsMdmRouteImport.update({
  id: '/mdm',
  path: '/mdm',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsInteroperabilityRoute =
  SolutionsInteroperabilityRouteImport.update({
    id: '/interoperability',
    path: '/interoperability',
    getParentRoute: () => SolutionsRoute,
  } as any)
const SolutionsIntelligenceRoute = SolutionsIntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsHesRoute = SolutionsHesRouteImport.update({
  id: '/hes',
  path: '/hes',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsCommunicationModulesRoute =
  SolutionsCommunicationModulesRouteImport.update({
    id: '/communication-modules',
    path: '/communication-modules',
    getParentRoute: () => SolutionsRoute,
  } as any)
const SolutionsArchitectureRoute = SolutionsArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => SolutionsRoute,
} as any)
const InsightUpdatesRoute = InsightUpdatesRouteImport.update({
  id: '/insight/updates',
  path: '/insight/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightNewsRoute = InsightNewsRouteImport.update({
  id: '/insight/news',
  path: '/insight/news',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightArticlesRoute = InsightArticlesRouteImport.update({
  id: '/insight/articles',
  path: '/insight/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightSlugRoute = InsightSlugRouteImport.update({
  id: '/insight/$slug',
  path: '/insight/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesPowerUtilitiesRoute =
  IndustriesPowerUtilitiesRouteImport.update({
    id: '/power-utilities',
    path: '/power-utilities',
    getParentRoute: () => IndustriesRoute,
  } as any)
const IndustriesGovernmentRoute = IndustriesGovernmentRouteImport.update({
  id: '/government',
  path: '/government',
  getParentRoute: () => IndustriesRoute,
} as any)
const ContactLocationsRoute = ContactLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => ContactRoute,
} as any)
const ContactDetailsRoute = ContactDetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => ContactRoute,
} as any)
const CompanyOverviewRoute = CompanyOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyLeadershipRoute = CompanyLeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyKaynesRoute = CompanyKaynesRouteImport.update({
  id: '/kaynes',
  path: '/kaynes',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyInvestorsRoute = CompanyInvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyGovernanceRoute = CompanyGovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyCultureRoute = CompanyCultureRouteImport.update({
  id: '/culture',
  path: '/culture',
  getParentRoute: () => CompanyRoute,
} as any)
const CareersStoriesRoute = CareersStoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => CareersRoute,
} as any)
const CareersCultureRoute = CareersCultureRouteImport.update({
  id: '/culture',
  path: '/culture',
  getParentRoute: () => CareersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/careers': typeof CareersRouteWithChildren
  '/company': typeof CompanyRouteWithChildren
  '/contact': typeof ContactRouteWithChildren
  '/experience': typeof ExperienceRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/manufacturing': typeof ManufacturingRoute
  '/privacy': typeof PrivacyRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/technology': typeof TechnologyRoute
  '/terms': typeof TermsRoute
  '/careers/culture': typeof CareersCultureRoute
  '/careers/stories': typeof CareersStoriesRoute
  '/company/culture': typeof CompanyCultureRoute
  '/company/governance': typeof CompanyGovernanceRoute
  '/company/investors': typeof CompanyInvestorsRoute
  '/company/kaynes': typeof CompanyKaynesRoute
  '/company/leadership': typeof CompanyLeadershipRoute
  '/company/overview': typeof CompanyOverviewRoute
  '/contact/details': typeof ContactDetailsRoute
  '/contact/locations': typeof ContactLocationsRoute
  '/industries/government': typeof IndustriesGovernmentRoute
  '/industries/power-utilities': typeof IndustriesPowerUtilitiesRoute
  '/insight/$slug': typeof InsightSlugRoute
  '/insight/articles': typeof InsightArticlesRoute
  '/insight/news': typeof InsightNewsRoute
  '/insight/updates': typeof InsightUpdatesRoute
  '/solutions/architecture': typeof SolutionsArchitectureRoute
  '/solutions/communication-modules': typeof SolutionsCommunicationModulesRoute
  '/solutions/hes': typeof SolutionsHesRoute
  '/solutions/intelligence': typeof SolutionsIntelligenceRoute
  '/solutions/interoperability': typeof SolutionsInteroperabilityRoute
  '/solutions/mdm': typeof SolutionsMdmRoute
  '/solutions/smart-meters': typeof SolutionsSmartMetersRoute
  '/insight/': typeof InsightIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/careers': typeof CareersRouteWithChildren
  '/company': typeof CompanyRouteWithChildren
  '/contact': typeof ContactRouteWithChildren
  '/experience': typeof ExperienceRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/manufacturing': typeof ManufacturingRoute
  '/privacy': typeof PrivacyRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/technology': typeof TechnologyRoute
  '/terms': typeof TermsRoute
  '/careers/culture': typeof CareersCultureRoute
  '/careers/stories': typeof CareersStoriesRoute
  '/company/culture': typeof CompanyCultureRoute
  '/company/governance': typeof CompanyGovernanceRoute
  '/company/investors': typeof CompanyInvestorsRoute
  '/company/kaynes': typeof CompanyKaynesRoute
  '/company/leadership': typeof CompanyLeadershipRoute
  '/company/overview': typeof CompanyOverviewRoute
  '/contact/details': typeof ContactDetailsRoute
  '/contact/locations': typeof ContactLocationsRoute
  '/industries/government': typeof IndustriesGovernmentRoute
  '/industries/power-utilities': typeof IndustriesPowerUtilitiesRoute
  '/insight/$slug': typeof InsightSlugRoute
  '/insight/articles': typeof InsightArticlesRoute
  '/insight/news': typeof InsightNewsRoute
  '/insight/updates': typeof InsightUpdatesRoute
  '/solutions/architecture': typeof SolutionsArchitectureRoute
  '/solutions/communication-modules': typeof SolutionsCommunicationModulesRoute
  '/solutions/hes': typeof SolutionsHesRoute
  '/solutions/intelligence': typeof SolutionsIntelligenceRoute
  '/solutions/interoperability': typeof SolutionsInteroperabilityRoute
  '/solutions/mdm': typeof SolutionsMdmRoute
  '/solutions/smart-meters': typeof SolutionsSmartMetersRoute
  '/insight': typeof InsightIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/careers': typeof CareersRouteWithChildren
  '/company': typeof CompanyRouteWithChildren
  '/contact': typeof ContactRouteWithChildren
  '/experience': typeof ExperienceRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/manufacturing': typeof ManufacturingRoute
  '/privacy': typeof PrivacyRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/technology': typeof TechnologyRoute
  '/terms': typeof TermsRoute
  '/careers/culture': typeof CareersCultureRoute
  '/careers/stories': typeof CareersStoriesRoute
  '/company/culture': typeof CompanyCultureRoute
  '/company/governance': typeof CompanyGovernanceRoute
  '/company/investors': typeof CompanyInvestorsRoute
  '/company/kaynes': typeof CompanyKaynesRoute
  '/company/leadership': typeof CompanyLeadershipRoute
  '/company/overview': typeof CompanyOverviewRoute
  '/contact/details': typeof ContactDetailsRoute
  '/contact/locations': typeof ContactLocationsRoute
  '/industries/government': typeof IndustriesGovernmentRoute
  '/industries/power-utilities': typeof IndustriesPowerUtilitiesRoute
  '/insight/$slug': typeof InsightSlugRoute
  '/insight/articles': typeof InsightArticlesRoute
  '/insight/news': typeof InsightNewsRoute
  '/insight/updates': typeof InsightUpdatesRoute
  '/solutions/architecture': typeof SolutionsArchitectureRoute
  '/solutions/communication-modules': typeof SolutionsCommunicationModulesRoute
  '/solutions/hes': typeof SolutionsHesRoute
  '/solutions/intelligence': typeof SolutionsIntelligenceRoute
  '/solutions/interoperability': typeof SolutionsInteroperabilityRoute
  '/solutions/mdm': typeof SolutionsMdmRoute
  '/solutions/smart-meters': typeof SolutionsSmartMetersRoute
  '/insight/': typeof InsightIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/careers'
    | '/company'
    | '/contact'
    | '/experience'
    | '/industries'
    | '/manufacturing'
    | '/privacy'
    | '/solutions'
    | '/technology'
    | '/terms'
    | '/careers/culture'
    | '/careers/stories'
    | '/company/culture'
    | '/company/governance'
    | '/company/investors'
    | '/company/kaynes'
    | '/company/leadership'
    | '/company/overview'
    | '/contact/details'
    | '/contact/locations'
    | '/industries/government'
    | '/industries/power-utilities'
    | '/insight/$slug'
    | '/insight/articles'
    | '/insight/news'
    | '/insight/updates'
    | '/solutions/architecture'
    | '/solutions/communication-modules'
    | '/solutions/hes'
    | '/solutions/intelligence'
    | '/solutions/interoperability'
    | '/solutions/mdm'
    | '/solutions/smart-meters'
    | '/insight/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/careers'
    | '/company'
    | '/contact'
    | '/experience'
    | '/industries'
    | '/manufacturing'
    | '/privacy'
    | '/solutions'
    | '/technology'
    | '/terms'
    | '/careers/culture'
    | '/careers/stories'
    | '/company/culture'
    | '/company/governance'
    | '/company/investors'
    | '/company/kaynes'
    | '/company/leadership'
    | '/company/overview'
    | '/contact/details'
    | '/contact/locations'
    | '/industries/government'
    | '/industries/power-utilities'
    | '/insight/$slug'
    | '/insight/articles'
    | '/insight/news'
    | '/insight/updates'
    | '/solutions/architecture'
    | '/solutions/communication-modules'
    | '/solutions/hes'
    | '/solutions/intelligence'
    | '/solutions/interoperability'
    | '/solutions/mdm'
    | '/solutions/smart-meters'
    | '/insight'
  id:
    | '__root__'
    | '/'
    | '/careers'
    | '/company'
    | '/contact'
    | '/experience'
    | '/industries'
    | '/manufacturing'
    | '/privacy'
    | '/solutions'
    | '/technology'
    | '/terms'
    | '/careers/culture'
    | '/careers/stories'
    | '/company/culture'
    | '/company/governance'
    | '/company/investors'
    | '/company/kaynes'
    | '/company/leadership'
    | '/company/overview'
    | '/contact/details'
    | '/contact/locations'
    | '/industries/government'
    | '/industries/power-utilities'
    | '/insight/$slug'
    | '/insight/articles'
    | '/insight/news'
    | '/insight/updates'
    | '/solutions/architecture'
    | '/solutions/communication-modules'
    | '/solutions/hes'
    | '/solutions/intelligence'
    | '/solutions/interoperability'
    | '/solutions/mdm'
    | '/solutions/smart-meters'
    | '/insight/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CareersRoute: typeof CareersRouteWithChildren
  CompanyRoute: typeof CompanyRouteWithChildren
  ContactRoute: typeof ContactRouteWithChildren
  ExperienceRoute: typeof ExperienceRoute
  IndustriesRoute: typeof IndustriesRouteWithChildren
  ManufacturingRoute: typeof ManufacturingRoute
  PrivacyRoute: typeof PrivacyRoute
  SolutionsRoute: typeof SolutionsRouteWithChildren
  TechnologyRoute: typeof TechnologyRoute
  TermsRoute: typeof TermsRoute
  InsightSlugRoute: typeof InsightSlugRoute
  InsightArticlesRoute: typeof InsightArticlesRoute
  InsightNewsRoute: typeof InsightNewsRoute
  InsightUpdatesRoute: typeof InsightUpdatesRoute
  InsightIndexRoute: typeof InsightIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manufacturing': {
      id: '/manufacturing'
      path: '/manufacturing'
      fullPath: '/manufacturing'
      preLoaderRoute: typeof ManufacturingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insight/': {
      id: '/insight/'
      path: '/insight'
      fullPath: '/insight/'
      preLoaderRoute: typeof InsightIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/smart-meters': {
      id: '/solutions/smart-meters'
      path: '/smart-meters'
      fullPath: '/solutions/smart-meters'
      preLoaderRoute: typeof SolutionsSmartMetersRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/mdm': {
      id: '/solutions/mdm'
      path: '/mdm'
      fullPath: '/solutions/mdm'
      preLoaderRoute: typeof SolutionsMdmRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/interoperability': {
      id: '/solutions/interoperability'
      path: '/interoperability'
      fullPath: '/solutions/interoperability'
      preLoaderRoute: typeof SolutionsInteroperabilityRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/intelligence': {
      id: '/solutions/intelligence'
      path: '/intelligence'
      fullPath: '/solutions/intelligence'
      preLoaderRoute: typeof SolutionsIntelligenceRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/hes': {
      id: '/solutions/hes'
      path: '/hes'
      fullPath: '/solutions/hes'
      preLoaderRoute: typeof SolutionsHesRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/communication-modules': {
      id: '/solutions/communication-modules'
      path: '/communication-modules'
      fullPath: '/solutions/communication-modules'
      preLoaderRoute: typeof SolutionsCommunicationModulesRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/architecture': {
      id: '/solutions/architecture'
      path: '/architecture'
      fullPath: '/solutions/architecture'
      preLoaderRoute: typeof SolutionsArchitectureRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/insight/updates': {
      id: '/insight/updates'
      path: '/insight/updates'
      fullPath: '/insight/updates'
      preLoaderRoute: typeof InsightUpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insight/news': {
      id: '/insight/news'
      path: '/insight/news'
      fullPath: '/insight/news'
      preLoaderRoute: typeof InsightNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insight/articles': {
      id: '/insight/articles'
      path: '/insight/articles'
      fullPath: '/insight/articles'
      preLoaderRoute: typeof InsightArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insight/$slug': {
      id: '/insight/$slug'
      path: '/insight/$slug'
      fullPath: '/insight/$slug'
      preLoaderRoute: typeof InsightSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/power-utilities': {
      id: '/industries/power-utilities'
      path: '/power-utilities'
      fullPath: '/industries/power-utilities'
      preLoaderRoute: typeof IndustriesPowerUtilitiesRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/government': {
      id: '/industries/government'
      path: '/government'
      fullPath: '/industries/government'
      preLoaderRoute: typeof IndustriesGovernmentRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/contact/locations': {
      id: '/contact/locations'
      path: '/locations'
      fullPath: '/contact/locations'
      preLoaderRoute: typeof ContactLocationsRouteImport
      parentRoute: typeof ContactRoute
    }
    '/contact/details': {
      id: '/contact/details'
      path: '/details'
      fullPath: '/contact/details'
      preLoaderRoute: typeof ContactDetailsRouteImport
      parentRoute: typeof ContactRoute
    }
    '/company/overview': {
      id: '/company/overview'
      path: '/overview'
      fullPath: '/company/overview'
      preLoaderRoute: typeof CompanyOverviewRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/leadership': {
      id: '/company/leadership'
      path: '/leadership'
      fullPath: '/company/leadership'
      preLoaderRoute: typeof CompanyLeadershipRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/kaynes': {
      id: '/company/kaynes'
      path: '/kaynes'
      fullPath: '/company/kaynes'
      preLoaderRoute: typeof CompanyKaynesRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/investors': {
      id: '/company/investors'
      path: '/investors'
      fullPath: '/company/investors'
      preLoaderRoute: typeof CompanyInvestorsRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/governance': {
      id: '/company/governance'
      path: '/governance'
      fullPath: '/company/governance'
      preLoaderRoute: typeof CompanyGovernanceRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/culture': {
      id: '/company/culture'
      path: '/culture'
      fullPath: '/company/culture'
      preLoaderRoute: typeof CompanyCultureRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/careers/stories': {
      id: '/careers/stories'
      path: '/stories'
      fullPath: '/careers/stories'
      preLoaderRoute: typeof CareersStoriesRouteImport
      parentRoute: typeof CareersRoute
    }
    '/careers/culture': {
      id: '/careers/culture'
      path: '/culture'
      fullPath: '/careers/culture'
      preLoaderRoute: typeof CareersCultureRouteImport
      parentRoute: typeof CareersRoute
    }
  }
}

interface CareersRouteChildren {
  CareersCultureRoute: typeof CareersCultureRoute
  CareersStoriesRoute: typeof CareersStoriesRoute
}

const CareersRouteChildren: CareersRouteChildren = {
  CareersCultureRoute: CareersCultureRoute,
  CareersStoriesRoute: CareersStoriesRoute,
}

const CareersRouteWithChildren =
  CareersRoute._addFileChildren(CareersRouteChildren)

interface CompanyRouteChildren {
  CompanyCultureRoute: typeof CompanyCultureRoute
  CompanyGovernanceRoute: typeof CompanyGovernanceRoute
  CompanyInvestorsRoute: typeof CompanyInvestorsRoute
  CompanyKaynesRoute: typeof CompanyKaynesRoute
  CompanyLeadershipRoute: typeof CompanyLeadershipRoute
  CompanyOverviewRoute: typeof CompanyOverviewRoute
}

const CompanyRouteChildren: CompanyRouteChildren = {
  CompanyCultureRoute: CompanyCultureRoute,
  CompanyGovernanceRoute: CompanyGovernanceRoute,
  CompanyInvestorsRoute: CompanyInvestorsRoute,
  CompanyKaynesRoute: CompanyKaynesRoute,
  CompanyLeadershipRoute: CompanyLeadershipRoute,
  CompanyOverviewRoute: CompanyOverviewRoute,
}

const CompanyRouteWithChildren =
  CompanyRoute._addFileChildren(CompanyRouteChildren)

interface ContactRouteChildren {
  ContactDetailsRoute: typeof ContactDetailsRoute
  ContactLocationsRoute: typeof ContactLocationsRoute
}

const ContactRouteChildren: ContactRouteChildren = {
  ContactDetailsRoute: ContactDetailsRoute,
  ContactLocationsRoute: ContactLocationsRoute,
}

const ContactRouteWithChildren =
  ContactRoute._addFileChildren(ContactRouteChildren)

interface IndustriesRouteChildren {
  IndustriesGovernmentRoute: typeof IndustriesGovernmentRoute
  IndustriesPowerUtilitiesRoute: typeof IndustriesPowerUtilitiesRoute
}

const IndustriesRouteChildren: IndustriesRouteChildren = {
  IndustriesGovernmentRoute: IndustriesGovernmentRoute,
  IndustriesPowerUtilitiesRoute: IndustriesPowerUtilitiesRoute,
}

const IndustriesRouteWithChildren = IndustriesRoute._addFileChildren(
  IndustriesRouteChildren,
)

interface SolutionsRouteChildren {
  SolutionsArchitectureRoute: typeof SolutionsArchitectureRoute
  SolutionsCommunicationModulesRoute: typeof SolutionsCommunicationModulesRoute
  SolutionsHesRoute: typeof SolutionsHesRoute
  SolutionsIntelligenceRoute: typeof SolutionsIntelligenceRoute
  SolutionsInteroperabilityRoute: typeof SolutionsInteroperabilityRoute
  SolutionsMdmRoute: typeof SolutionsMdmRoute
  SolutionsSmartMetersRoute: typeof SolutionsSmartMetersRoute
}

const SolutionsRouteChildren: SolutionsRouteChildren = {
  SolutionsArchitectureRoute: SolutionsArchitectureRoute,
  SolutionsCommunicationModulesRoute: SolutionsCommunicationModulesRoute,
  SolutionsHesRoute: SolutionsHesRoute,
  SolutionsIntelligenceRoute: SolutionsIntelligenceRoute,
  SolutionsInteroperabilityRoute: SolutionsInteroperabilityRoute,
  SolutionsMdmRoute: SolutionsMdmRoute,
  SolutionsSmartMetersRoute: SolutionsSmartMetersRoute,
}

const SolutionsRouteWithChildren = SolutionsRoute._addFileChildren(
  SolutionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CareersRoute: CareersRouteWithChildren,
  CompanyRoute: CompanyRouteWithChildren,
  ContactRoute: ContactRouteWithChildren,
  ExperienceRoute: ExperienceRoute,
  IndustriesRoute: IndustriesRouteWithChildren,
  ManufacturingRoute: ManufacturingRoute,
  PrivacyRoute: PrivacyRoute,
  SolutionsRoute: SolutionsRouteWithChildren,
  TechnologyRoute: TechnologyRoute,
  TermsRoute: TermsRoute,
  InsightSlugRoute: InsightSlugRoute,
  InsightArticlesRoute: InsightArticlesRoute,
  InsightNewsRoute: InsightNewsRoute,
  InsightUpdatesRoute: InsightUpdatesRoute,
  InsightIndexRoute: InsightIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
